# Generated by Django 4.2.1 on 2023-12-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Express', 'Express'), ('Standard', 'Standard')], default='Standard', max_length=8),
            preserve_default=False,
        ),
    ]
