# Generated by Django 4.2.1 on 2023-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_delivery_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='credit_card',
            new_name='registered_credit_card',
        ),
        migrations.AddField(
            model_name='order',
            name='credit_card',
            field=models.CharField(default=1234567891234567, max_length=16),
            preserve_default=False,
        ),
    ]
